id: P008268
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3MS94
  title: དམ་ཚིག་དང་སྡོམ་པའི་རྣམ་བཞག་འདོད་འཇོ་དབང་རྒྱལ།
  author: ''
  volumes:
    8cdf3530fde445969c0bdbd44cbf76eb:
      image_group_id: I3MS96
      title: ''
      volume_number: 1
      total_pages: 157
      base_file: v001.txt
