id: I4464929A
legacy_id: P008268
ocr_import_info:
  bdrc_scan_id: W3MS94
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T08:50:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:09:07.585468+00:00'
last_modified: 2022-09-04 01:09:15.387166
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3MS94
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3MS94
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཚིག་དང་སྡོམ་པའི་རྣམ་བཞག་འདོད་འཇོ་དབང་རྒྱལ།
  author: བྲག་རི་དམ་ཚིག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.4955847287504408
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I3MS96:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3MS96
      total_pages: 157
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3MS96.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.4955847287504408
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
